/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/kit-tests/': RouteRecordInfo<'/admin/kit-tests/', '/admin/kit-tests', Record<never, never>, Record<never, never>>,
    '/admin/kits/': RouteRecordInfo<'/admin/kits/', '/admin/kits', Record<never, never>, Record<never, never>>,
    '/admin/questions/': RouteRecordInfo<'/admin/questions/', '/admin/questions', Record<never, never>, Record<never, never>>,
    '/admin/questions/[id]/': RouteRecordInfo<'/admin/questions/[id]/', '/admin/questions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/questions/[id]/update': RouteRecordInfo<'/admin/questions/[id]/update', '/admin/questions/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/questions/create': RouteRecordInfo<'/admin/questions/create', '/admin/questions/create', Record<never, never>, Record<never, never>>,
    '/admin/topics/': RouteRecordInfo<'/admin/topics/', '/admin/topics', Record<never, never>, Record<never, never>>,
    '/admin/vocabularies/': RouteRecordInfo<'/admin/vocabularies/', '/admin/vocabularies', Record<never, never>, Record<never, never>>,
    '/forgot-password': RouteRecordInfo<'/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }
}
