/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/kit-tests/': RouteRecordInfo<'/admin/kit-tests/', '/admin/kit-tests', Record<never, never>, Record<never, never>>,
    '/admin/kits/': RouteRecordInfo<'/admin/kits/', '/admin/kits', Record<never, never>, Record<never, never>>,
    '/admin/questions/': RouteRecordInfo<'/admin/questions/', '/admin/questions', Record<never, never>, Record<never, never>>,
    '/admin/questions/[id]/': RouteRecordInfo<'/admin/questions/[id]/', '/admin/questions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/questions/[id]/update': RouteRecordInfo<'/admin/questions/[id]/update', '/admin/questions/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/questions/create': RouteRecordInfo<'/admin/questions/create', '/admin/questions/create', Record<never, never>, Record<never, never>>,
    '/admin/topics/': RouteRecordInfo<'/admin/topics/', '/admin/topics', Record<never, never>, Record<never, never>>,
    '/admin/vocabularies/': RouteRecordInfo<'/admin/vocabularies/', '/admin/vocabularies', Record<never, never>, Record<never, never>>,
    '/admin/vocabularies/[id]/update': RouteRecordInfo<'/admin/vocabularies/[id]/update', '/admin/vocabularies/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/vocabularies/create': RouteRecordInfo<'/admin/vocabularies/create', '/admin/vocabularies/create', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/question/[part]/': RouteRecordInfo<'/dashboard/question/[part]/', '/dashboard/question/:part', { part: ParamValue<true> }, { part: ParamValue<false> }>,
    '/dashboard/question/[part]/practice/[numOfQuestion]/': RouteRecordInfo<'/dashboard/question/[part]/practice/[numOfQuestion]/', '/dashboard/question/:part/practice/:numOfQuestion', { part: ParamValue<true>, numOfQuestion: ParamValue<true> }, { part: ParamValue<false>, numOfQuestion: ParamValue<false> }>,
    '/dashboard/results/[id]/': RouteRecordInfo<'/dashboard/results/[id]/', '/dashboard/results/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/results/[id]/detail': RouteRecordInfo<'/dashboard/results/[id]/detail', '/dashboard/results/:id/detail', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/results/[id]/list-choice': RouteRecordInfo<'/dashboard/results/[id]/list-choice', '/dashboard/results/:id/list-choice', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/results-test/[id]/': RouteRecordInfo<'/dashboard/results-test/[id]/', '/dashboard/results-test/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/results-test/[id]/detail': RouteRecordInfo<'/dashboard/results-test/[id]/detail', '/dashboard/results-test/:id/detail', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/tests/': RouteRecordInfo<'/dashboard/tests/', '/dashboard/tests', Record<never, never>, Record<never, never>>,
    '/dashboard/tests/[id]/': RouteRecordInfo<'/dashboard/tests/[id]/', '/dashboard/tests/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/tests/[id]/practice/': RouteRecordInfo<'/dashboard/tests/[id]/practice/', '/dashboard/tests/:id/practice', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/topics/': RouteRecordInfo<'/dashboard/topics/', '/dashboard/topics', Record<never, never>, Record<never, never>>,
    '/dashboard/topics/[id]/': RouteRecordInfo<'/dashboard/topics/[id]/', '/dashboard/topics/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/topics/[id]/learn': RouteRecordInfo<'/dashboard/topics/[id]/learn', '/dashboard/topics/:id/learn', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/topics/[id]/result': RouteRecordInfo<'/dashboard/topics/[id]/result', '/dashboard/topics/:id/result', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/forgot-password': RouteRecordInfo<'/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }
}
