import { config } from 'dotenv'

config({
    path:
        process.env.NODE_ENV === 'production' ? undefined : '.env.development',
})

export const CREDENTIALS = process.env.CREDENTIALS === 'true'
export const {
    NODE_ENV,
    PORT,
    LOG_FORMAT,
    LOG_DIR,
    ORIGIN,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET,
    DATABASE_URL,
    RESET_PASS_TOKEN_SECRET,
    REDIS_HOST,
    REDIS_PORT,
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_UNIVERSE_DOMAIN,
    FIREBASE_DATABASE_URL,
    SIGNATURE_SECRET,
    PUBLIC_DOMAIN,
    BOT_ENDPOINT,
    MAIL_USER,
    MAIL_PASS,
    API_KEY,
    VERIFY_EMAIL_TOKEN_SECRET,
    STRIPE_SECRET_KEY,
    DB_HOST,
    DB_PORT,
    DB_USER,
    DB_PASSWORD,
    DB_NAME,
    CLIENT_URL,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
} = process.env
