version: '3.9'

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

  db:
    container_name: toeic-max-db
    image: postgres:latest
    ports:
      - '5435:5432'
    volumes:
      - data:/data/db
    restart: 'unless-stopped'
    networks:
      - backend
  redis:
    container_name: toeic-max-redis
    image: redis:latest
    ports:
      - '6389:6379'
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
