export { default as ForgotPasswordForm } from './ForgotPasswordForm.vue'
export { default as KitForm } from './KitForm.vue'
export { default as KitTestForm } from './KitTestForm.vue'
export { default as LoginForm } from './LoginForm.vue'
export { default as RegisterForm } from './RegisterForm.vue'
